fix: uploadPart cannot upload stream and etag error
minio/minio-js pull request #1334
Opened 2024-08-14 07:06 UTC by MilkChan01

S3 API can upload a binary file in the body. We need this feature for users to implement slicing and uploading files themselves.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html

2024-08-27 06:30 UTC, prakashsvmx requested changes

2024-08-27 06:30 UTC, prakashsvmx commented on src/internal/client.ts
> +    // const partRes = uploadPartParser(body)
Please remove the commented lines if not used.

2024-09-04 08:56 UTC, prakashsvmx commented on src/internal/client.ts
> +    // const partRes = uploadPartParser(body)
@MilkChan01  Could you please fix this ?

2024-10-24 20:18 UTC, harshavardhana commented on src/internal/client.ts
> +    // const partRes = uploadPartParser(body)
```suggestion
```

2024-10-25 02:03 UTC, prakashsvmx approved these changes

2024-10-25 02:14 UTC, harshavardhana approved these changes

2024-10-25 02:14 UTC, merged