versionId support in presigned url
minio/minio-js pull request #913
Opened 2021-03-11 13:40 UTC by prakashsvmx

VersionId support in pre signed url ( get)

2021-03-13 18:30 UTC, kannappanr submitted a review, later dismissed
LGTM

2021-03-17 01:13 UTC, ebozduman requested changes

2021-03-17 01:13 UTC, ebozduman commented on examples/presigned-getobject-request-date.js
> +var requestDate = new Date('2017-01-01')
We don't need this old date. We can set `requestDate` to current date
```suggestion
var requestDate = new Date()
```

2021-03-17 01:13 UTC, ebozduman commented on examples/presigned-getobject-request-date.js
> +s3Client.presignedGetObject('my-bucketname', 'my-objectname', 1000, {versionId:"10fa9946-3f64-4137-a58f-888065c0732e"}, new Date('2017-01-01'), function(e, presignedUrl) {
The same comment as before:
```suggestion
s3Client.presignedGetObject('my-bucketname', 'my-objectname', 1000, {versionId:"10fa9946-3f64-4137-a58f-888065c0732e"}, new Date(), function(e, presignedUrl) {
```

2021-03-17 10:32 UTC, prakashsvmx commented
@ebozduman  Thank you for the review. I have addressed the comments. PTAL

2021-03-17 11:52 UTC, ebozduman approved these changes
LGTM

2021-03-17 11:54 UTC, ebozduman commented
Oops!
@prakashsvmx 
Please take a look into the build failures

2021-03-20 10:37 UTC, kannappanr commented
@prakashsvmx Please resolve the conflicts

2021-03-22 07:23 UTC, ebozduman submitted a review, later dismissed
LGTM

2021-05-26 23:13 UTC, kannappanr approved these changes
LGTM

2021-05-27 04:31 UTC, merged