Get/Set Object locking
minio/minio-js pull request #919
Opened 2021-04-07 11:16 UTC by prakashsvmx

Get/Set Object locking

2021-04-09 08:53 UTC, ebozduman requested changes

2021-04-09 08:53 UTC, ebozduman commented on docs/API.md
> +    console.log("Success",lockConfig)
```suggestion
    console.log(lockConfig)
```

2021-04-09 08:53 UTC, ebozduman commented on examples/get-object-lock-config.js
> +  console.log("Success", lockConfig)
```suggestion
  console.log(lockConfig)
```

2021-04-09 08:53 UTC, ebozduman commented on examples/set-object-lock-config.js
> +})
I think `delete` should be a separate example and needs to be removed from the `set/put` example.

2021-04-09 17:38 UTC, kannappanr commented
```
S3Error: Missing required header for this request: Content-MD5
    at Object.parseError (/home/kannappan/work/github.com/minio/minio-js/dist/main/xml-parsers.js:83:11)
    at /home/kannappan/work/github.com/minio/minio-js/dist/main/transformers.js:158:22
    at DestroyableTransform._flush (/home/kannappan/work/github.com/minio/minio-js/dist/main/transformers.js:82:10)
    at DestroyableTransform.prefinish (/home/kannappan/work/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:310:20)
    at prefinish (/home/kannappan/work/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/home/kannappan/work/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/home/kannappan/work/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/home/kannappan/work/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (_stream_readable.js:660:10) {
  code: 'InvalidRequest',
  requestid: '0YAJM1FM2QTW719D',
  hostid: '8w89j+mgEKvwn7AIJl2GqCkGFuw+80C8JE5hQ6+bHmHSw34WDJIEjdPrQynIkGHwMPsc4qcA4jw=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

2021-04-09 17:38 UTC, kannappanr commented
`content-md5` needs to be calculated for the body

2021-04-12 08:58 UTC, prakashsvmx commented
@kannappanr  @ebozduman  Thank you for the review.

@kannappanr  I have updated and ran functional tests in standalone, distributed and gateway mode. 

Request you to PTAL.

2021-04-13 05:12 UTC, ebozduman commented
There is a failure after fixing the missing md5 information in the request.
Here is my script:
```
var Minio = require('./dist/main/minio')
var s3Client = new Minio.Client({
  endPoint: 's3.amazonaws.com',
  // port: 9001,
  useSSL: true,
  region: 'us-east-1',
  accessKey: 'xxxxxxxxx',
  secretKey: 'xxxxxxxxxxxxxxxxx',
})
bucket = "retlock"
//Set Object lock on a bucket
s3Client.setObjectLockConfig(bucket, {mode:"COMPLIANCE",unit:'Days', validity:10}, function (err){
  if (err) {
    return console.log(err)
  }
  console.log("Success")
})

$ node run-set-object-lock-config.js
S3Error: The XML you provided was not well-formed or did not validate against our published schema
    at Object.parseError (/home/ersan/work/src/github.com/minio/minio-js/dist/main/xml-parsers.js:83:11)
    at /home/ersan/work/src/github.com/minio/minio-js/dist/main/transformers.js:158:22
    at DestroyableTransform._flush (/home/ersan/work/src/github.com/minio/minio-js/dist/main/transformers.js:82:10)
    at DestroyableTransform.prefinish (/home/ersan/work/src/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:315:20)
    at prefinish (/home/ersan/work/src/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/home/ersan/work/src/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/home/ersan/work/src/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/home/ersan/work/src/github.com/minio/minio-js/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:678:10) {
  code: 'MalformedXML',
  requestid: 'ZAMYAZKN34YER6FY',
  hostid: 'ZtH13VM6AzpL2oLHOKKaS0ZD2XL5ETbI8xtF/zsLH30I2NbRk1MCI6oJHoUiEEbBKGGTyayTNVM=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

2021-04-13 07:07 UTC, prakashsvmx commented
@ebozduman @kannappanr  The issue was an extra key `Unit` was passed which the minio server ignored but it failed in S3. 
I have removed the same and tested against s3. It works fine now.

2021-04-13 08:36 UTC, ebozduman approved these changes
LGTM

2021-04-22 20:49 UTC, kannappanr approved these changes
LGTM

2021-04-22 20:49 UTC, merged