Fix tag request signing and response codes
minio/minio-js pull request #968
Opened 2021-09-28 15:47 UTC by prakashsvmx

Fixes #964

- Some inconsistencies in response codes of APIs
- Fix broken md5 calculation (S3)

Tested against:

- [x] S3
- [x] MinIO Server ( Local/ play)

2021-11-30 05:06 UTC, ebozduman commented
@prakashsvmx,

I am ready to approve, but it looks like there are some conflicts in your branch.

2021-12-01 04:37 UTC, prakashsvmx commented
@ebozduman thank you. I have resolved the conflicts. PTAL.

2021-12-01 09:08 UTC, harshavardhana requested changes

2021-12-01 09:08 UTC, harshavardhana commented on src/main/minio.js
> +    headers['Content-MD5'] =toMd5(payload)
```suggestion
    headers['Content-MD5'] = toMd5(payload)
```

2021-12-01 09:08 UTC, harshavardhana commented on src/main/helpers.js
> +export  const validateStatusCode = (statusCode) =>{
```suggestion
export const validateStatusCode = (statusCode) =>{
```

2021-12-01 09:08 UTC, harshavardhana commented on src/main/helpers.js
> +  return true
where is this function used?

2021-12-01 09:08 UTC, harshavardhana commented on src/main/helpers.js
> +  return  payloadBuf
```suggestion
  return payloadBuf
```

2021-12-01 09:37 UTC, prakashsvmx commented on src/main/helpers.js
> +  return true
Thank you. I will remove it.

2021-12-01 09:51 UTC, harshavardhana approved these changes

2021-12-01 09:51 UTC, prakashsvmx commented
@harshavardhana thank you so much for the review.

2021-12-03 09:05 UTC, ebozduman approved these changes
LGTM

2021-12-03 09:06 UTC, merged

2021-12-04 08:02 UTC, mapleeit commented
Hi. Could I ask for a new patch for this fix? It really blocks lots of functionalities. Thanks

2021-12-04 17:14 UTC, harshavardhana commented
> Hi. Could I ask for a new patch for this fix? It really blocks lots of functionalities. Thanks

Soon!

2021-12-07 03:32 UTC, mapleeit commented
Is the `crypto-browserify` missing in `package.json`? After bump up to `7.0.24`, an error has been raised: Cannot find module 'crypto-browserify'

2021-12-07 03:36 UTC, harshavardhana commented
> Is the `crypto-browserify` missing in `package.json`? After bump up to `7.0.24`, an error has been raised: Cannot find module 'crypto-browserify'

yep looks like 

> src/main/helpers.js:var Crypto = require('crypto-browserify')

2021-12-07 03:37 UTC, harshavardhana commented
@prakashsvmx ^^

2021-12-07 05:00 UTC, prakashsvmx commented
@harshavardhana  Thank you so much for the quick fix.