Run Tests in GitHub CI using actions instead of play
minio/minio-js pull request #987
Opened 2021-12-16 04:11 UTC by prakashsvmx

Run Tests in GitHub CI using actions instead of play

How to test:
Linux:
I have used https://github.com/nektos/act to run the actions locally and verify the status. 

Windows:
To be tested.

2021-12-22 07:11 UTC, ebozduman requested changes

2021-12-22 07:34 UTC, prakashsvmx commented on src/test/functional/functional-tests.js
> +    const objectNameSpecialChars="äöüex ®©µÄÆÐÕæŒƕƩǅ 01000000 0x40 u0040 amȡȹɆple&0a!-_.'()&$@=;+,.pdf"
Thank you. Yes. I will check the os and use the object name accordingly.

2021-12-30 04:52 UTC, harshavardhana approved these changes

2022-01-06 18:29 UTC, harshavardhana commented
ping @kanagarajkm @ebozduman

2022-01-07 08:03 UTC, kanagarajkm commented
@prakashsvmx Windows test is failing 

```
  1) functional tests
       Special Characters test on a prefix and an object
         putObject(bucketName, objectName, stream)_bucketName:minio-js-test-obj-sppre22d99c8b-c3b2-4fe9-b5dc-4e323810d03d, _objectName:SpecialMenùäöüexPrefix/äöüex ®©µÄÆÐÕæŒƕƩǅ 01000000 0x40 @ amȡȹɆple&0a!-_.*'()&$@=;:+,?<>.pdf, stream:100Kib:
     S3Error: Object name contains unsupported characters.
```

2022-01-07 08:17 UTC, harshavardhana commented
> putObject(bucketName, objectName, stream)_bucketName:minio-js-test-obj-sppre22d99c8b-c3b2-4fe9-b5dc-4e323810d03d, _objectName:SpecialMenùäöüexPrefix/äöüex ®©µÄÆÐÕæŒƕƩǅ 01000000 0x40 @ amȡȹɆple&0a!-_.*'()&$@=;:+,?<>.pdf, stream:100Kib:

Windows won't support these characters @prakashsvmx you would have to skip this test on windows

2022-01-07 08:37 UTC, prakashsvmx commented
@harshavardhana  @kanagarajkm  Thank you for the review.

`isWindowsPlatform` check  is introduced in this PR. 
 interesting finding is that old CI jobs for windows never failed for this test case.

2022-01-07 10:16 UTC, harshavardhana approved these changes

2022-01-07 10:16 UTC, harshavardhana commented on .github/workflows/nodejs-windows.yml
> +          npm run test
```suggestion
          npm run test

```

2022-01-07 10:16 UTC, harshavardhana commented on .github/workflows/nodejs.yml
> +          npm run test
```suggestion
          npm run test

```

2022-01-07 18:28 UTC, harshavardhana approved these changes

2022-01-08 01:24 UTC, ebozduman approved these changes
LGTM

2022-01-08 05:02 UTC, merged